### ISSUE TITLE
slacker.Error: invalid_auth

### ISSUE THREAD

**Issue by phbissiwu** [sgratzl/slack-cleaner#102]
When I run slack-cleaner, I get the below error.
I tried to update the token and change the permission scope but I still get the same error. 

Running slack-cleaner v0.7.4
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner', 'console_scripts', 'slack-cleaner')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ec2-user/slack-cleaner/src/slack-cleaner/slack_cleaner/cli.py", line 84, in <module>
    init_user_dict()
  File "/home/ec2-user/slack-cleaner/src/slack-cleaner/slack_cleaner/cli.py", line 66, in init_user_dict
    res = slack.users.list().body
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 331, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: invalid_auth

**To Reproduce**

1. 

**Expected behavior**

**Screenshots**

**Context**

- Version:
- Python Version: 

**Additional context**

**Comment by lyaschuchenko** [comment]
you use incorrect token

**Comment by sgratzl** [comment]
without more context or token information, there is not much I can do
