### ISSUE TITLE
AttributeError raised when trying to delete messages posted by a bot user

### ISSUE THREAD

**Issue by duong2179** [sgratzl/slack-cleaner#15]
```
duong-dajgja:~ duong2179$ slack-cleaner --token xoxb-xxx-xxxxxx --message --group my-private-channel --user bot_uname
Running slack-cleaner v0.3.0
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner', 'console_scripts', 'slack-cleaner')()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/slack_cleaner/cli.py", line 337, in main
    message_cleaner()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/slack_cleaner/cli.py", line 305, in message_cleaner
    _user_id = get_user_id_by_name(args.user_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/slack_cleaner/cli.py", line 224, in get_user_id_by_name
    for k, v in user_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by sgratzl** [comment]
you are using an old version of this package. The original package hosted on pip is by the original author and is not compatible with python 3. This fork is. However, you have to install it using 
```
pip install -e git+https://github.com/sgratzl/slack-cleaner.git#egg=slack-cleaner
```
