### ISSUE TITLE
dev: unicode error in cli application

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/slack-cleaner#25]
coming from https://github.com/sgratzl/slack-cleaner/issues/7#issuecomment-385272763
```
Traceback (most recent call last):
File "/usr/local/bin/slack-cleaner", line 9, in
load_entry_point('slack-cleaner2==0.1.0', 'console_scripts', 'slack-cleaner')()
File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 209, in main
_show_infos(slack)
File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 23, in _show_infos
_print_dict('users', {u.id: '{} = {}'.format(u.name, u.real_name) for u in slack.users})
File "/Library/Python/2.7/site-packages/slack_cleaner2-0.1.0-py2.7.egg/slack_cleaner2/cli.py", line 23, in
_print_dict('users', {u.id: '{} = {}'.format(u.name, u.real_name) for u in slack.users})
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128
```

**Comment by sgratzl** [comment]
see https://github.com/sgratzl/slack-cleaner/blob/develop/slack_cleaner2/cli.py#L23
