### ISSUE TITLE
user_dict keyerror

### ISSUE THREAD

**Issue by palewire** [sgratzl/slack-cleaner#59]
```Traceback (most recent call last):
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner', 'console_scripts', 'slack-cleaner')()
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/src/slack-cleaner/slack_cleaner/cli.py", line 471, in main
    message_cleaner()
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/src/slack-cleaner/slack_cleaner/cli.py", line 400, in message_cleaner
    clean_channel(channel_id, channel_type, time_range, user_id=_user_id, bot=args.bot)
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/src/slack-cleaner/slack_cleaner/cli.py", line 163, in clean_channel
    delete_message_on_channel(channel_id, m)
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/src/slack-cleaner/slack_cleaner/cli.py", line 219, in delete_message_on_channel
    get_user_name(message), get_message_or_first_attachment_text(message))
  File "/home/palewire/.virtualenvs/slack-cleaner-y1JoDDbN/src/slack-cleaner/slack_cleaner/cli.py", line 191, in get_user_name
    return user_dict[_id]
KeyError: 'UG50GR0SG'
```

**Comment by sgratzl** [comment]
Hi, can you take a look at https://github.com/sgratzl/slack_cleaner2 and check whether this user id is in the resolved list of user? Moreover, did you delete some users from slack at some point?

**Comment by sgratzl** [comment]
I implemented a more conservative version in the master branch

**Comment by sgratzl** [comment]
@palewire can you try out the latest master branch?
