### ISSUE TITLE
KeyError: 'ims' when deleting direct messages

### ISSUE THREAD

**Issue by mmannerm** [sgratzl/slack-cleaner#81]
**Describe the bug**
Unable to clean up direct messages because of KeyError: 'ims'

**To Reproduce**
```
slack-cleaner --token <token> --message --direct <user> --user "*" --before 20200401 --perform
```

**Expected behavior**
All direct messages sent to and from user <user> will be deleted.

**Screenshots**
```
Running slack-cleaner v0.7.2
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 509, in main
    message_cleaner()
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 429, in message_cleaner
    _channels = resolve_channels()
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 397, in resolve_channels
    _channels.extend([(id, name, 'direct') for (id, name) in get_direct_ids_by_pattern(args.direct_name, not args.regex)])
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner/cli.py", line 333, in get_direct_ids_by_pattern
    ims = res['ims']
KeyError: 'ims'
```

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.3
 - Python 3.7.7 (homebrew)
- Version 0.7.2

**Comment by sgratzl** [comment]
should be fixed with v0.7.3
