### ISSUE TITLE
Unable to delete messages from private channel

### ISSUE THREAD

**Issue by forwoodthinker** [sgratzl/slack-cleaner#82]
When I try to delete messages from a private channel I get `slacker.Error: not_authed`. I have all permission scopes mentioned in the readme added to the Slack App, and am able to delete messages from public channels. The administrator and owner of the App is in this private channel.

**To Reproduce**
Run `slack-cleaner --token XXXX --message --channel my-private-channel --user "*" --as_user --perform`

**Expected behavior**
Messages are deleted from the private channel.

**Screenshots**

**Context**

- Version:
- Python Version: 2.7

**Additional context**
Full error output:
```
Running slack-cleaner v0.7.3
Traceback (most recent call last):
  File "/Users/Eleanor/Library/Python/2.7/bin/slack-cleaner", line 9, in <module>
    load_entry_point('slack-cleaner==0.7.3', 'console_scripts', 'slack-cleaner')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Eleanor/Downloads/src/slack-cleaner/slack_cleaner/cli.py", line 84, in <module>
    init_user_dict()
  File "/Users/Eleanor/Downloads/src/slack-cleaner/slack_cleaner/cli.py", line 66, in init_user_dict
    res = slack.users.list().body
  File "/Users/Eleanor/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 331, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/Users/Eleanor/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/Users/Eleanor/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: not_authed
```

**Comment by sgratzl** [comment]
seems like fails already when resolving users: `res = slack.users.list().body`

do you have the `users:read` permission?

**Comment by forwoodthinker** [comment]
Yes, I have all permissions listed in the readme:
```
channels:history
channels:read
chat:write
files:read
files:write
groups:history
groups:read
im:history
im:read
mpim:history
mpim:read
users:read
```

**Comment by sgratzl** [comment]
I see, `slacker.Error: not_authed` is according to the slack api: `not_authed | No authentication token provided.`. 

can you post the line you use to delete messages from a public channel?

**Comment by forwoodthinker** [comment]
It turns out that I had an issue with passing my token through to the command which was solved by using the `SLACK_TOKEN` environment variable. Deleting works for all channels now!
