### ISSUE TITLE
slacker.Error: thread_not_found

### ISSUE THREAD

**Issue by Deleetdk** [sgratzl/slack-cleaner#83]
Trying to delete all content from a Slack. Only remaining are the general channel messages. The code to clean this breaks periodically related to threads.

**To Reproduce**
Using the command from this issue: https://github.com/sgratzl/slack-cleaner/issues/70

`slack-cleaner --token XXX --message --channel general --before 20210919 --user "*" --perform --log --as_user`

Works fine for a while, then breaks with:

```
Traceback (most recent call last):
  File "/home/emil/.local/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner', 'console_scripts', 'slack-cleaner')()
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 508, in main
    message_cleaner()
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 437, in message_cleaner
    clean_channel(channel_id, time_range, user_id=_user_id, bot=args.bot)
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 211, in clean_channel
    _clean_messages_impl(list_f, channel_id, time_range, user_id, bot)
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 179, in _clean_messages_impl
    clean_replies(channel_id, m.get('thread_ts', m['ts']), time_range, user_id, bot)
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 204, in clean_replies
    _clean_messages_impl(list_f, channel_id, time_range, user_id, bot, thread_ts)
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 141, in _clean_messages_impl
    res = list_f(latest, oldest).body
  File "/home/emil/src/slack-cleaner/slack_cleaner/cli.py", line 202, in list_f
    return slack.conversations.replies(channel_id, thread_ts, latest=latest, oldest=oldest, limit=1000)
  File "/home/emil/.local/lib/python3.6/site-packages/slacker/__init__.py", line 253, in replies
    'limit': limit
  File "/home/emil/.local/lib/python3.6/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/home/emil/.local/lib/python3.6/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: thread_not_found
```

**Expected behavior**
It should keep deleting without errors.

**Screenshots**
![Screenshot from 2020-06-23 00-26-26](https://user-images.githubusercontent.com/6759913/85341334-30a8c280-b4e8-11ea-9cb0-c74f94eff9d4.png)

**Context**

- Version: newest from Github as of writing, Version 0.7.3
- Python Version: python3.6

**Comment by sgratzl** [comment]
I wrapped it with a try/catch for now to avoid that this error is raised but just silently handled
