### ISSUE TITLE
slacker.Error: invalid_auth

### ISSUE THREAD

**Issue by lacostenycoder** [sgratzl/slack-cleaner#91]
**To Reproduce**

1. Install from development branch
2. follow instructions to [configure app](https://github.com/sgratzl/slack-cleaner#configuring-app)
3 try to run 
```
slack-cleaner --token $TOKEN --message --channel ci-builds --user "*" --before 20201201
```

**Expected behavior**

Expect script to work and start deleting messages
**Screenshots**

**Context**
I get the following error trace
```
Running slack-cleaner v0.7.4
Traceback (most recent call last):
  File "/Users/lacoste/.pyenv/versions/3.7.5/bin/slack-cleaner", line 11, in <module>
    load_entry_point('slack-cleaner', 'console_scripts', 'slack-cleaner')()
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/lacoste/src/slack-cleaner/slack_cleaner/cli.py", line 84, in <module>
    init_user_dict()
  File "/Users/lacoste/src/slack-cleaner/slack_cleaner/cli.py", line 66, in init_user_dict
    res = slack.users.list().body
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/slacker/__init__.py", line 331, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/Users/lacoste/.pyenv/versions/3.7.5/lib/python3.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: invalid_auth
```
- Version: 0.7.4
- Python Version: 3.7.5

**Additional context**

**Comment by lacostenycoder** [comment]
channel was a bot channel so I had to use

```
slack-cleaner --token $TOKEN --message --channel ci-builds --botname "circle-ci" --before 20201201 --perform --as_user
```
