### ISSUE TITLE
AttributeError: 'Slacker' object has no attribute 'conversations'

### ISSUE THREAD

**Issue by blackthroat** [sgratzl/slack-cleaner#92]
When I attempt to delete direct messages, I receive `AttributeError: 'Slacker' object has no attribute 'conversations'` error message.

**To Reproduce**

1. slack-cleaner --token xoxp-REDACTED --message --direct blackthroat --user otheruser --as_user --rate 10 --log  --perform

**Expected behavior**

The last time that I know this successfully worked was at the beginning of December. I have not updated macOS or Python recently.

**Screenshots**

Running slack-cleaner v0.7.4
Traceback (most recent call last):
  File "./slack-cleaner", line 8, in <module>
    sys.exit(main())
  File "/Users/blackthroat/Library/Python/2.7/lib/python/site-packages/slack_cleaner/cli.py", line 516, in main
    message_cleaner()
  File "/Users/blackthroat/Library/Python/2.7/lib/python/site-packages/slack_cleaner/cli.py", line 436, in message_cleaner
    _channels = resolve_channels()
  File "/Users/blackthroat/Library/Python/2.7/lib/python/site-packages/slack_cleaner/cli.py", line 404, in resolve_channels
    _channels.extend([(id, name, 'direct') for (id, name) in get_direct_ids_by_pattern(args.direct_name, not args.regex)])
  File "/Users/blackthroat/Library/Python/2.7/lib/python/site-packages/slack_cleaner/cli.py", line 338, in get_direct_ids_by_pattern
    res = slack.conversations.list(types='im', limit=1000).body
AttributeError: 'Slacker' object has no attribute 'conversations'

**Context**

- Version: 0.7.4
- Python Version: 2.7.14

**Additional context**

Confirmed the permissions are set correctly as well as the token is correct.

**Comment by blackthroat** [comment]
I see someone else experienced this, https://github.com/sgratzl/slack-cleaner/issues/57

Ran `pip install slack-cleaner` again and that fixed the problem.

```
Installing collected packages: slacker
  Attempting uninstall: slacker
    Found existing installation: slacker 0.10.0
    Uninstalling slacker-0.10.0:
      Successfully uninstalled slacker-0.10.0
Successfully installed slacker-0.14.0
```
