### ISSUE TITLE
slacker.Error: method_deprecated

### ISSUE THREAD

**Issue by sapzxc** [sgratzl/slack-cleaner#94]
slack changed their API, so this tool does not work anymore.

`slacker.Error: method_deprecated`.

Detailed description of changes: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by sgratzl** [comment]
before filing an issue please make sure that you are using the latest version. what version are you using?

**Comment by sapzxc** [comment]
`# pip-3.8 install slack-cleaner`
`# slack-cleaner --token ... `
`Running slack-cleaner v0.3.0
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 9, in <module>
    load_entry_point('slack-cleaner==0.3.0', 'console_scripts', 'slack-cleaner')()
  File "build/bdist.macosx-10.12-intel/egg/slack_cleaner/cli.py", line 352, in main
  File "build/bdist.macosx-10.12-intel/egg/slack_cleaner/cli.py", line 297, in message_cleaner
  File "build/bdist.macosx-10.12-intel/egg/slack_cleaner/cli.py", line 245, in get_channel_id_by_name
  File "build/bdist.macosx-10.12-intel/egg/slacker/__init__.py", line 209, in list
  File "build/bdist.macosx-10.12-intel/egg/slacker/__init__.py", line 68, in get
  File "build/bdist.macosx-10.12-intel/egg/slacker/__init__.py", line 63, in _request
slacker.Error: method_deprecated`

**Comment by sgratzl** [comment]
the latest version is 0.7.4: https://github.com/sgratzl/slack-cleaner/releases

**Comment by sapzxc** [comment]
works. Thanks a lot. It was my fault.
